# NOTE: This file should be named prek.toml but Renovate does not support it yet.
repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-json5
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-xml
      - id: mixed-line-ending
      - id: check-symlinks
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-executables-have-shebangs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-ast
      - id: check-shebang-scripts-are-executable
      - id: requirements-txt-fixer

  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e # frozen: v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a # frozen: v2.4.2
    hooks:
      - id: codespell

  - repo: https://github.com/rhysd/actionlint
    rev: 393031adb9afb225ee52ae2ccd7a5af5525e03e8 # frozen: v1.7.11
    hooks:
      - id: actionlint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95 # frozen: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: e05c5c0818279e5ac248ac9e954431ba58865e61 # frozen: v0.15.7
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: e3daa3b1abb0f966fc89f674fdf01eebd84c2eec # frozen: 0.10.12
    hooks:
      - id: uv-lock

  - repo: https://github.com/ansible/ansible-lint
    rev: 8ba9595a4acd1b906eb75568b34f6ef592cd1528 # frozen: v26.3.0
    hooks:
      - id: ansible-lint

  - repo: https://github.com/hadolint/hadolint
    rev: 57e1618d78fd469a92c1e584e8c9313024656623 # frozen: v2.14.0
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 3766ad839ad3a74558031510b3bc9872bb1d9980 # frozen: v0.22.0
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 8c1eeecc5ffed2694436e385b2c69e8f786933e6 # frozen: 43.86.1
    hooks:
      - id: renovate-config-validator
        args: [--strict]
