name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "*"

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@ddb6493160c38f9f1244d911f0d47147520d5e2f # main
    secrets: inherit
