name: Common Cron Checks

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

permissions: write-all

jobs:
  common-cron-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-cron-checks.yaml@6516f14ca8e986a00e6b69ddfacfefd116ea2377 # main
    secrets: inherit
