name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "**"

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@f64fc47c34183bfbad53c56824ff17000ba80d8b # main
    secrets: inherit
