name: Common Cron Checks

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

permissions: write-all

jobs:
  common-cron-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-cron-checks.yaml@c25aa77664b0baaa85eced1c26f595c9c7fd32bf # main
    secrets: inherit
