name: Release on Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  build-and-push:
    uses: neteye-platform/repo-commons/.github/workflows/build-docker-image.yaml@c8b32d369d20cca27bc2ff8ace6e20330156c7f0 # main
    with:
      working-directory: "."
      dockerfile-path: "./Dockerfile"
      image-name: ${{ github.event.repository.name }}
      push: true
    secrets: inherit
