name: Release on Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write

    uses: neteye-platform/repo-commons/.github/workflows/build-docker-image.yaml@ddb6493160c38f9f1244d911f0d47147520d5e2f # main
    with:
      working-directory: "."
      dockerfile-path: "./Dockerfile"
      image-name: ${{ github.event.repository.name }}
      push: true
    secrets: inherit
