name: Release on Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write

    uses: neteye-platform/repo-commons/.github/workflows/build-docker-image.yaml@f83f660abb176d6cd448b89c21e89a00bb61cf95 # main
    with:
      working-directory: "."
      dockerfile-path: "./Dockerfile"
      image-name: ${{ github.event.repository.name }}
      push: true
    secrets: inherit
